Repository KeypDemoCorp/awesome-api-backend, pull requests merged in 2022-06, with the labels that each got.

#16 Implement two-factor authentication
  implement-two-factor-authentication.md
Labels: enhancement, bug-minor

#11 Add toaster to notify of action results
  add-toaster-to-notify-of-action-results.md
Labels: enhancement

#19 Test branch
  README.md
  hash.json
Labels: critical, incident, bug

#13 Allow users to login with Google
  allow-users-to-login-with-google.md
Labels: enhancement, incident

#25 To review
  temporary
Labels: documentation, enhancement

#12 WIP: Batch of UI improvements
  wip-batch-of-ui-improvements.md
Labels: minor, bug
